# Dataset configuration for generating a small test dataset

dataset_name: small_test_dataset
description: "A small dataset for testing the dataset generator pipeline"
version: 1.0

simulation_groups:
  - name: chordal_test
    num_simulations: 5
    base_config: configs/chordal_major.yaml
    use_rhythm: true
    param_ranges:
      randomness_factor: [0.2, 0.8]
      variation_probability: [0.3, 0.7]
      sequence_length: [4, 8]
    rhythm_param_ranges:
      subdivision: [4, 8]
      
  - name: melodic_test
    num_simulations: 5
    base_config: configs/melodic_random.yaml
    use_rhythm: true
    param_ranges:
      randomness_factor: [0.2, 0.7]
      variation_probability: [0.3, 0.6]
      sequence_length: [6, 10]

# Global dataset generation settings
settings:
  save_midi: true
  save_stats: true
