# Configuration for generating traditional using optimized interval weights
generation_type: chordal
start_pc:
- 0
- 4
- 7
progression: true
progression_type: random
sequence_length: 8
randomness_factor: 0.4
variation_probability: 0.6
allowed_operations:
- transpose
- substitute_note
- add_note
- remove_note
constraints:
  vary_chord: true
midi_properties:
  tempo: 100
  base_octave: 4
  note_duration: 0.75
interval_weights:
  1: 2.0
  2: 1.5
  3: 1.0
  4: 1.0
  5: 0.5
  6: 0.5
