# Configuration demonstrating interval weighting for generating jazz-like progressions

# Generation properties
generation_type: chordal
start_pc: [0, 4, 7, 11]  # Cmaj7
progression: true
progression_type: random
sequence_length: 8

# Transformation control
allowed_operations:
  - transpose
  - substitute_note
  - add_note
  - remove_note

# Randomness controls
randomness_factor: 0.6
variation_probability: 0.7

# Interval weights - using a predefined profile
interval_weights: "jazzy"

# Alternatively, custom interval weights:
# interval_weights:
#   1: 0.8   # minor 2nds/major 7ths
#   2: 1.2   # major 2nds/minor 7ths
#   3: 1.4   # minor 3rds/major 6ths
#   4: 1.3   # major 3rds/minor 6ths
#   5: 0.7   # perfect 4ths/5ths
#   6: 1.3   # tritones

# Constraints
constraints:
  vary_chord: true
  maintain_cardinality: true

# MIDI properties
midi_properties:
  tempo: 90
  base_octave: 4
  note_duration: 0.8
  velocity: 70
